### ISSUE TITLE
Deletion of labels removes corresponding JSON (Review mode)

### ISSUE THREAD

**Issue by umayerr** [theSKAILab/AnNER#17]
When a reviewer deletes any label, the corresponding JSON for that annotation is removed. Instead of being deleted, it should be recorded as "Rejected" in the JSON, and the annotation should no longer be displayed in the tool.

**Comment by npease18** [comment]
This will clash with the preexisting mode "Rejected". I can make this work in the current session that the reviewer is working in (i.e when the reviewer deletes a block, it disappears on the screen and is recorded as 'rejected'). However, if the reviewer exports this file and re-imports it, the deletion will not persist and will instead be imported as a "rejected annotation". If you are okay with modifying the exported JSON format to add a new field, I can make this persistent.

**Comment by npease18** [comment]
Fixed with #39 as discussed in the meeting.
