### ISSUE TITLE
Toggle behavior and incorrect JSON (Review mode)

### ISSUE THREAD

**Issue by umayerr** [theSKAILab/AnNER#18]
When clicking the toggle for a single annotation, the system should only update the JSON for that specific annotation. However, it currently updates the JSON for all annotations. Additionally, the un-toggle function does not work on subsequent clicks.

**Comment by npease18** [comment]
To clarify, this is the review toggle denoting that the term has been review? I can implement this but I thought the intended use was to denote that the term has been review in one form or another. If its been touched, it doesn't make sense to enable the toggle unless I am misunderstanding.

**Comment by npease18** [comment]
I received your email with guidance on the functionality. I will fix accordingly!
