### ISSUE TITLE
Annotations disappear on screen (become empty in JSON) (Annotation mode)

### ISSUE THREAD

**Issue by umayerr** [theSKAILab/AnNER#9]
The first paragraph was annotated, saved, and then the second paragraph was selected (paragraph automatically switches to the next one when the `SAVE` button is pressed). Afterward, the `BACK` button was used to navigate to the first paragraph, where it was observed that the previously made annotations had disappeared. The `SAVE` button was then used to return to the second paragraph. Upon exporting the JSON file, it was noticed that the annotation for the first paragraph was missing.

NOTE: Fixed the issue, and it's working now. But need to check if the solution is sustainable.

**Comment by npease18** [comment]
Presumed fixed as problem has not manifested
